name: release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    permissions:
      contents: write # to create a new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodule source)
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Run GoReleaser (Pro)
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean
        env:
          CONTAINER_ENGINE: docker
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
